### PR TITLE
Add AIX support

### PR DESCRIPTION
**Pull request by tssva**
Most of these changes are based upon those NattyNarwhal has made in his efforts to port oksh to AIX. Many of the changes needed to support AIX would also be needed for potential ports to other platforms such as HP-UX or Solaris. I created checks in the configure script and added implementations. For io.c and tty.c I integrated the changes he made to support systems without F_DUPFD_CLOEXEC, but wrapped them in ifdef's so F_DUPFD_CLOEXEC is used on systems which do support it. It provides protection from potential race conditions when FD_CLOEXEC is not applied atomically. 

Aside from integrating the changes from NattyNarwhal I added the asprintf implementation from the compat library of libressl and created a check for asprintf.

### CODE REVIEW

**Comment by ibara** [comment]
Cool. I'm just waiting for this to have a confirmed working build on AIX (I don't have one either) then I'll merge.

**Comment by tssva** [comment]
Added checks for `st_mtim` and `st_mtimespec`. If `st_mtim` is not present and `st_mtimespec` is then `st_mtim` is defined as `st_mtimespec`. If neither is found fall back to using `st_mtime` by defining `st_mtim` as `st_mtime` and `timespeccmp` as `timespeccmp(tsp, usp, cmp) (tsp) cmp (usp)`. 

Added the defines, compiler and linker flags specific to AIX. With these changes oksh is building properly on AIX.

**Comment by NattyNarwhal** [comment]
I'm using oksh as my login shell on an AIX system. So far, it hasn't blown up.

FWIW, it'll compile fine with both GCC 4.9 and 6.4 on AIX.

**Comment by ibara** [comment]
Alright let's merge this then.

**Pull request merged**
